### ISSUE TITLE
I want to know keyboard shortcuts of kazam

### ISSUE THREAD

**Issue by mkh10086** [hzbd/kazam#15]
```
Keyboard shortcuts
------------------

SUPER-CTRL-Q - Quit
SUPER-CTRL-W - Show/Hide main window
SUPER-CTRL-R - Start Recording
SUPER-CTRL-F - Finish Recording
```
from the document, i knew that, there are four shortcuts for screencast.
 i found another one `SUPER-CTRL-P - Pause/continue Recording`.

but there is no keyboard shortcuts for screenshot, why?
who knows all the shortcuts? please tell me, thank you

**Comment by ghost** [comment]
there are FIVE shortcuts:
from [Frontend/indicator.py](https://github.com/hzbd/kazam/blob/491869ac29860a19254fa8c226f75314a7eee83d/kazam/frontend/indicator.py#L108):

>             <Super><Ctrl>R -> "start-request"
>             <Super><Ctrl>F -> "stop-request"
>             <Super><Ctrl>P -> "pause-request"
>             <Super><Ctrl>W -> "show-request"
>             <Super><Ctrl>Q -> "quit-request"

Guess you could code a keyboard shortcut for screenshot without a lot of problem...

**Comment by isleshocky77** [comment]
It would be great if these shortcuts were displayed somewhere in Kazam and/or configurable. But displaying it in the app would be extremely beneficial for now.

**Comment by maheshbasnet089** [comment]
In the upcoming updates , it will be helpful if you display keyboard shortcut somewhere in the the preferences ...

**Comment by niknah** [comment]
This commit adds the instructions to the "help" button on the menu...
https://github.com/niknah/kazam/commit/6d9c5074ad812cf99d8a0274d4dab38273a7c9a3
